REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''
REDDIT_USERNAME = ''
REDDIT_PASSWORD = ''
REDDIT_USER_AGENT = ''
REDDIT_SUBREDDIT = ''

SUBREDDIT_META_FLAIR_ID = ''
SUBREDDIT_MODLIST = [

]
SUBREDDIT_REPORT_THRESHOLD_DANGER = 2
SUBREDDIT_REPORT_THRESHOLD_NOTICE = 0
SUBREDDIT_PROBLEM_SUBS = [

]

SLACK_CHANNEL_LIST = {
    "bot-notifications": ""
}
SLACK_STATUS_CHANNEL = ''
SLAC_NOTICE_CHANNEL = ''
SLACK_ALERT_CHANNEL = ''
SLACK_DANGER_CHANNEL = ''
SLACK_SOCIAL_CHANNEL = ''

BOT_NAME = ''
